### ISSUE TITLE
Additional style for visited links

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/www-clarin-eu_src#3]
Add something along the lines of
```less
.mark-visited-links a, a.mark-visited:visited {
  color: lighten(@link-color, 20%); //example, evaluate actual colour to use!
}
```

so that visited links will be visually distinct if the right (container) class is applied, e.g.
```html
<p>
    <a>Does not change colour if visited</a>
    <a class="mark-visited">Changes colour if visited</a>
</p>

<p class="mark-visited-links">
   <a>Changes colour if visited</a>
</p>
```
